const LANGUAGES = {
  en: { name: "English", native: "English", flag: "🇬🇧" },
  hi: { name: "Hindi", native: "हिंदी", flag: "🇮🇳" },
  bn: { name: "Bengali", native: "বাংলা", flag: "🇧🇩" },
  te: { name: "Telugu", native: "తెలుగు", flag: "🇮🇳" },
  mr: { name: "Marathi", native: "मराठी", flag: "🇮🇳" },
  ta: { name: "Tamil", native: "தமிழ்", flag: "🇮🇳" },
  gu: { name: "Gujarati", native: "ગુજરાતી", flag: "🇮🇳" },
  kn: { name: "Kannada", native: "ಕನ್ನಡ", flag: "🇮🇳" },
  ml: { name: "Malayalam", native: "മലയാളം", flag: "🇮🇳" },
  pa: { name: "Punjabi", native: "ਪੰਜਾਬੀ", flag: "🇮🇳" },
  ur: { name: "Urdu", native: "اردو", flag: "🇵🇰" },
  fr: { name: "French", native: "Français", flag: "🇫🇷" },
  es: { name: "Spanish", native: "Español", flag: "🇪🇸" },
  ar: { name: "Arabic", native: "العربية", flag: "🇸🇦" },
  zh: { name: "Chinese", native: "中文", flag: "🇨🇳" },
  ja: { name: "Japanese", native: "日本語", flag: "🇯🇵" },
  de: { name: "German", native: "Deutsch", flag: "🇩🇪" },
  pt: { name: "Portuguese", native: "Português", flag: "🇧🇷" },
  ru: { name: "Russian", native: "Русский", flag: "🇷🇺" },
  sw: { name: "Swahili", native: "Kiswahili", flag: "🇰🇪" },
};

// UI translations: key = UI string, value = translation in that language
const UI_TEXT = {
  en: {
    tagline: "Learn English the smart way",
    subtitle: "Select your native language to get started",
    chooseLanguage: "Choose Your Language",
    continue: "Continue",
    searchLang: "Search language...",
    welcomeBack: "Welcome back",
    signIn: "Sign In",
    signUp: "Sign Up",
    continueGoogle: "Continue with Google",
    orEmail: "or use email",
    sendMagicLink: "Send Magic Link",
    dashboard: "Dashboard",
    vocabulary: "Vocabulary",
    grammar: "Grammar",
    reading: "Reading",
    conversation: "Daily Conversation",
    quiz: "Quiz",
    progress: "My Progress",
    profile: "Profile",
    wordOfDay: "Word of the Day",
    dailyGoals: "Daily Goals",
    achievements: "Achievements",
    meaning: "Meaning",
    example: "Example",
    translation: "Translation",
    loading: "Loading SpeakRise",
    nativeMeaning: (word, meaning) => `${word} means "${meaning}" in your language`,
  },
  hi: {
    tagline: "स्मार्ट तरीके से English सीखें",
    subtitle: "शुरू करने के लिए अपनी भाषा चुनें",
    chooseLanguage: "अपनी भाषा चुनें",
    continue: "आगे बढ़ें",
    searchLang: "भाषा खोजें...",
    welcomeBack: "वापसी पर स्वागत है",
    signIn: "साइन इन",
    signUp: "साइन अप",
    continueGoogle: "Google से जारी रखें",
    orEmail: "या Email से",
    sendMagicLink: "Magic Link भेजें",
    dashboard: "डैशबोर्ड",
    vocabulary: "शब्द-भंडार",
    grammar: "व्याकरण",
    reading: "पठन",
    conversation: "दैनिक वार्तालाप",
    quiz: "प्रश्नोत्तरी",
    progress: "मेरी प्रगति",
    profile: "प्रोफाइल",
    wordOfDay: "आज का शब्द",
    dailyGoals: "आज के लक्ष्य",
    achievements: "उपलब्धियाँ",
    meaning: "अर्थ",
    example: "उदाहरण",
    translation: "अनुवाद",
    loading: "SpeakRise लोड हो रहा है",
    nativeMeaning: (word, meaning) => `"${word}" का अर्थ है "${meaning}"`,
  },
  bn: {
    tagline: "স্মার্টভাবে English শিখুন",
    subtitle: "শুরু করতে আপনার ভাষা বেছে নিন",
    chooseLanguage: "আপনার ভাষা বেছে নিন",
    continue: "চালিয়ে যান",
    searchLang: "ভাষা খুঁজুন...",
    welcomeBack: "আবার স্বাগতম",
    signIn: "সাইন ইন",
    signUp: "সাইন আপ",
    continueGoogle: "Google দিয়ে চালিয়ে যান",
    orEmail: "বা Email দিয়ে",
    sendMagicLink: "Magic Link পাঠান",
    dashboard: "ড্যাশবোর্ড",
    vocabulary: "শব্দভান্ডার",
    grammar: "ব্যাকরণ",
    reading: "পাঠ",
    conversation: "দৈনিক কথোপকথন",
    quiz: "কুইজ",
    progress: "আমার অগ্রগতি",
    profile: "প্রোফাইল",
    wordOfDay: "আজকের শব্দ",
    dailyGoals: "আজকের লক্ষ্য",
    achievements: "অর্জন",
    meaning: "অর্থ",
    example: "উদাহরণ",
    translation: "অনুবাদ",
    loading: "SpeakRise লোড হচ্ছে",
    nativeMeaning: (word, meaning) => `"${word}" মানে "${meaning}"`,
  },
  te: {
    tagline: "తెలివైన పద్ధతిలో English నేర్చుకోండి",
    subtitle: "ప్రారంభించడానికి మీ భాషను ఎంచుకోండి",
    chooseLanguage: "మీ భాషను ఎంచుకోండి",
    continue: "కొనసాగించు",
    searchLang: "భాష వెతకండి...",
    welcomeBack: "తిరిగి స్వాగతం",
    signIn: "సైన్ ఇన్",
    signUp: "సైన్ అప్",
    continueGoogle: "Google తో కొనసాగించు",
    orEmail: "లేదా Email తో",
    sendMagicLink: "Magic Link పంపండి",
    dashboard: "డాష్‌బోర్డ్",
    vocabulary: "పదజాలం",
    grammar: "వ్యాకరణం",
    reading: "పఠనం",
    conversation: "దైనందిన సంభాషణ",
    quiz: "క్విజ్",
    progress: "నా పురోగతి",
    profile: "ప్రొఫైల్",
    wordOfDay: "నేటి పదం",
    dailyGoals: "నేటి లక్ష్యాలు",
    achievements: "విజయాలు",
    meaning: "అర్థం",
    example: "ఉదాహరణ",
    translation: "అనువాదం",
    loading: "SpeakRise లోడ్ అవుతోంది",
    nativeMeaning: (word, meaning) => `"${word}" అంటే "${meaning}"`,
  },
  ta: {
    tagline: "புத்திசாலித்தனமான முறையில் English கற்கவும்",
    subtitle: "தொடங்க உங்கள் மொழியை தேர்ந்தெடுக்கவும்",
    chooseLanguage: "உங்கள் மொழியை தேர்ந்தெடுக்கவும்",
    continue: "தொடரவும்",
    searchLang: "மொழி தேடுக...",
    welcomeBack: "மீண்டும் வரவேற்கிறோம்",
    signIn: "உள்நுழைக",
    signUp: "பதிவு செய்க",
    continueGoogle: "Google மூலம் தொடரவும்",
    orEmail: "அல்லது Email மூலம்",
    sendMagicLink: "Magic Link அனுப்பு",
    dashboard: "டாஷ்போர்டு",
    vocabulary: "சொல்லகராதி",
    grammar: "இலக்கணம்",
    reading: "வாசிப்பு",
    conversation: "தினசரி உரையாடல்",
    quiz: "வினாடி வினா",
    progress: "என் முன்னேற்றம்",
    profile: "சுயவிவரம்",
    wordOfDay: "இன்றைய சொல்",
    dailyGoals: "இன்றைய இலக்குகள்",
    achievements: "சாதனைகள்",
    meaning: "பொருள்",
    example: "எடுத்துக்காட்டு",
    translation: "மொழிபெயர்ப்பு",
    loading: "SpeakRise ஏற்றுகிறது",
    nativeMeaning: (word, meaning) => `"${word}" என்றால் "${meaning}"`,
  },
  mr: {
    tagline: "हुशारीने English शिका",
    subtitle: "सुरू करण्यासाठी तुमची भाषा निवडा",
    chooseLanguage: "तुमची भाषा निवडा",
    continue: "पुढे जा",
    searchLang: "भाषा शोधा...",
    welcomeBack: "परत स्वागत आहे",
    signIn: "साइन इन",
    signUp: "साइन अप",
    continueGoogle: "Google सह सुरू ठेवा",
    orEmail: "किंवा Email ने",
    sendMagicLink: "Magic Link पाठवा",
    dashboard: "डॅशबोर्ड",
    vocabulary: "शब्दसंग्रह",
    grammar: "व्याकरण",
    reading: "वाचन",
    conversation: "दैनंदिन संवाद",
    quiz: "प्रश्नमंजुषा",
    progress: "माझी प्रगती",
    profile: "प्रोफाइल",
    wordOfDay: "आजचा शब्द",
    dailyGoals: "आजची उद्दिष्टे",
    achievements: "उपलब्धी",
    meaning: "अर्थ",
    example: "उदाहरण",
    translation: "भाषांतर",
    loading: "SpeakRise लोड होत आहे",
    nativeMeaning: (word, meaning) => `"${word}" म्हणजे "${meaning}"`,
  },
  gu: {
    tagline: "સ્માર્ટ રીતે English શીખો",
    subtitle: "શરૂ કરવા માટે તમારી ભાષા પસંદ કરો",
    chooseLanguage: "તમારી ભાષા પસંદ કરો",
    continue: "આગળ વધો",
    searchLang: "ભાષા શોધો...",
    welcomeBack: "પાછા સ્વાગત છે",
    signIn: "સાઇન ઇન",
    signUp: "સાઇન અપ",
    continueGoogle: "Google સાથે ચાલુ રાખો",
    orEmail: "અથવા Email વડે",
    sendMagicLink: "Magic Link મોકલો",
    dashboard: "ડેશબોર્ડ",
    vocabulary: "શબ્દભંડોળ",
    grammar: "વ્યાકરણ",
    reading: "વાંચન",
    conversation: "રોજની વાતચીત",
    quiz: "ક્વિઝ",
    progress: "મારી પ્રગતિ",
    profile: "પ્રોફાઇલ",
    wordOfDay: "આજનો શબ્દ",
    dailyGoals: "આજના લક્ષ્યો",
    achievements: "સિદ્ધિઓ",
    meaning: "અર્થ",
    example: "ઉદાહરણ",
    translation: "અનુવાદ",
    loading: "SpeakRise લોડ થઈ રહ્યું છે",
    nativeMeaning: (word, meaning) => `"${word}" નો અર્થ "${meaning}" છે`,
  },
  kn: {
    tagline: "ಸ್ಮಾರ್ಟ್ ರೀತಿಯಲ್ಲಿ English ಕಲಿಯಿರಿ",
    subtitle: "ಪ್ರಾರಂಭಿಸಲು ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    chooseLanguage: "ನಿಮ್ಮ ಭಾಷೆ ಆಯ್ಕೆ ಮಾಡಿ",
    continue: "ಮುಂದುವರಿಸಿ",
    searchLang: "ಭಾಷೆ ಹುಡುಕಿ...",
    welcomeBack: "ಮತ್ತೆ ಸ್ವಾಗತ",
    signIn: "ಸೈನ್ ಇನ್",
    signUp: "ಸೈನ್ ಅಪ್",
    continueGoogle: "Google ಮೂಲಕ ಮುಂದುವರಿಸಿ",
    orEmail: "ಅಥವಾ Email ಮೂಲಕ",
    sendMagicLink: "Magic Link ಕಳುಹಿಸಿ",
    dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    vocabulary: "ಶಬ್ದಕೋಶ",
    grammar: "ವ್ಯಾಕರಣ",
    reading: "ಓದುವಿಕೆ",
    conversation: "ದೈನಂದಿನ ಸಂವಾದ",
    quiz: "ಕ್ವಿಜ್",
    progress: "ನನ್ನ ಪ್ರಗತಿ",
    profile: "ಪ್ರೊಫೈಲ್",
    wordOfDay: "ಇಂದಿನ ಪದ",
    dailyGoals: "ಇಂದಿನ ಗುರಿಗಳು",
    achievements: "ಸಾಧನೆಗಳು",
    meaning: "ಅರ್ಥ",
    example: "ಉದಾಹರಣೆ",
    translation: "ಅನುವಾದ",
    loading: "SpeakRise ಲೋಡ್ ಆಗುತ್ತಿದೆ",
    nativeMeaning: (word, meaning) => `"${word}" ಎಂದರೆ "${meaning}"`,
  },
  ml: {
    tagline: "ബുദ്ധിപൂർവ്വം English പഠിക്കൂ",
    subtitle: "ആരംഭിക്കാൻ നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കുക",
    chooseLanguage: "നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കുക",
    continue: "തുടരുക",
    searchLang: "ഭാഷ തിരയുക...",
    welcomeBack: "തിരിച്ചുവരവിൽ സ്വാഗതം",
    signIn: "സൈൻ ഇൻ",
    signUp: "സൈൻ അപ്",
    continueGoogle: "Google ഉപയോഗിച്ച് തുടരുക",
    orEmail: "അല്ലെങ്കിൽ Email വഴി",
    sendMagicLink: "Magic Link അയയ്ക്കുക",
    dashboard: "ഡാഷ്‌ബോർഡ്",
    vocabulary: "പദശേഖരം",
    grammar: "വ്യാകരണം",
    reading: "വായന",
    conversation: "ദൈനംദിന സംഭാഷണം",
    quiz: "ക്വിസ്",
    progress: "എന്റെ പുരോഗതി",
    profile: "പ്രൊഫൈൽ",
    wordOfDay: "ഇന്നത്തെ വാക്ക്",
    dailyGoals: "ഇന്നത്തെ ലക്ഷ്യങ്ങൾ",
    achievements: "നേട്ടങ്ങൾ",
    meaning: "അർത്ഥം",
    example: "ഉദാഹരണം",
    translation: "വിവർത്തനം",
    loading: "SpeakRise ലോഡ് ചെയ്യുന്നു",
    nativeMeaning: (word, meaning) => `"${word}" എന്നാൽ "${meaning}"`,
  },
  pa: {
    tagline: "ਸਮਾਰਟ ਤਰੀਕੇ ਨਾਲ English ਸਿੱਖੋ",
    subtitle: "ਸ਼ੁਰੂ ਕਰਨ ਲਈ ਆਪਣੀ ਭਾਸ਼ਾ ਚੁਣੋ",
    chooseLanguage: "ਆਪਣੀ ਭਾਸ਼ਾ ਚੁਣੋ",
    continue: "ਅੱਗੇ ਵਧੋ",
    searchLang: "ਭਾਸ਼ਾ ਖੋਜੋ...",
    welcomeBack: "ਵਾਪਸ ਸੁਆਗਤ ਹੈ",
    signIn: "ਸਾਈਨ ਇਨ",
    signUp: "ਸਾਈਨ ਅੱਪ",
    continueGoogle: "Google ਨਾਲ ਜਾਰੀ ਰੱਖੋ",
    orEmail: "ਜਾਂ Email ਨਾਲ",
    sendMagicLink: "Magic Link ਭੇਜੋ",
    dashboard: "ਡੈਸ਼ਬੋਰਡ",
    vocabulary: "ਸ਼ਬਦ-ਭੰਡਾਰ",
    grammar: "ਵਿਆਕਰਣ",
    reading: "ਪੜ੍ਹਨਾ",
    conversation: "ਰੋਜ਼ਾਨਾ ਗੱਲਬਾਤ",
    quiz: "ਕੁਇਜ਼",
    progress: "ਮੇਰੀ ਤਰੱਕੀ",
    profile: "ਪ੍ਰੋਫਾਈਲ",
    wordOfDay: "ਅੱਜ ਦਾ ਸ਼ਬਦ",
    dailyGoals: "ਅੱਜ ਦੇ ਟੀਚੇ",
    achievements: "ਪ੍ਰਾਪਤੀਆਂ",
    meaning: "ਅਰਥ",
    example: "ਉਦਾਹਰਣ",
    translation: "ਅਨੁਵਾਦ",
    loading: "SpeakRise ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ",
    nativeMeaning: (word, meaning) => `"${word}" ਦਾ ਮਤਲਬ "${meaning}" ਹੈ`,
  },
  ur: {
    tagline: "ذہین طریقے سے English سیکھیں",
    subtitle: "شروع کرنے کے لیے اپنی زبان چنیں",
    chooseLanguage: "اپنی زبان چنیں",
    continue: "جاری رکھیں",
    searchLang: "زبان تلاش کریں...",
    welcomeBack: "واپس خوش آمدید",
    signIn: "سائن ان",
    signUp: "سائن اپ",
    continueGoogle: "Google سے جاری رکھیں",
    orEmail: "یا Email سے",
    sendMagicLink: "Magic Link بھیجیں",
    dashboard: "ڈیش بورڈ",
    vocabulary: "ذخیرہ الفاظ",
    grammar: "گرامر",
    reading: "پڑھنا",
    conversation: "روزمرہ گفتگو",
    quiz: "کوئز",
    progress: "میری ترقی",
    profile: "پروفائل",
    wordOfDay: "آج کا لفظ",
    dailyGoals: "آج کے اہداف",
    achievements: "کامیابیاں",
    meaning: "معنی",
    example: "مثال",
    translation: "ترجمہ",
    loading: "SpeakRise لوڈ ہو رہا ہے",
    nativeMeaning: (word, meaning) => `"${word}" کا مطلب "${meaning}" ہے`,
  },
  fr: {
    tagline: "Apprenez l'anglais de manière intelligente",
    subtitle: "Choisissez votre langue pour commencer",
    chooseLanguage: "Choisissez votre langue",
    continue: "Continuer",
    searchLang: "Rechercher une langue...",
    welcomeBack: "Bon retour",
    signIn: "Se connecter",
    signUp: "S'inscrire",
    continueGoogle: "Continuer avec Google",
    orEmail: "ou avec Email",
    sendMagicLink: "Envoyer le lien magique",
    dashboard: "Tableau de bord",
    vocabulary: "Vocabulaire",
    grammar: "Grammaire",
    reading: "Lecture",
    conversation: "Conversation quotidienne",
    quiz: "Quiz",
    progress: "Ma progression",
    profile: "Profil",
    wordOfDay: "Mot du jour",
    dailyGoals: "Objectifs du jour",
    achievements: "Succès",
    meaning: "Signification",
    example: "Exemple",
    translation: "Traduction",
    loading: "Chargement de SpeakRise",
    nativeMeaning: (word, meaning) => `"${word}" signifie "${meaning}"`,
  },
  es: {
    tagline: "Aprende inglés de manera inteligente",
    subtitle: "Elige tu idioma para empezar",
    chooseLanguage: "Elige tu idioma",
    continue: "Continuar",
    searchLang: "Buscar idioma...",
    welcomeBack: "Bienvenido de nuevo",
    signIn: "Iniciar sesión",
    signUp: "Registrarse",
    continueGoogle: "Continuar con Google",
    orEmail: "o con Email",
    sendMagicLink: "Enviar enlace mágico",
    dashboard: "Panel",
    vocabulary: "Vocabulario",
    grammar: "Gramática",
    reading: "Lectura",
    conversation: "Conversación diaria",
    quiz: "Cuestionario",
    progress: "Mi progreso",
    profile: "Perfil",
    wordOfDay: "Palabra del día",
    dailyGoals: "Metas del día",
    achievements: "Logros",
    meaning: "Significado",
    example: "Ejemplo",
    translation: "Traducción",
    loading: "Cargando SpeakRise",
    nativeMeaning: (word, meaning) => `"${word}" significa "${meaning}"`,
  },
  ar: {
    tagline: "تعلم الإنجليزية بطريقة ذكية",
    subtitle: "اختر لغتك للبدء",
    chooseLanguage: "اختر لغتك",
    continue: "متابعة",
    searchLang: "ابحث عن لغة...",
    welcomeBack: "مرحباً بعودتك",
    signIn: "تسجيل الدخول",
    signUp: "التسجيل",
    continueGoogle: "المتابعة مع Google",
    orEmail: "أو عبر البريد الإلكتروني",
    sendMagicLink: "إرسال الرابط السحري",
    dashboard: "لوحة التحكم",
    vocabulary: "المفردات",
    grammar: "القواعد",
    reading: "القراءة",
    conversation: "محادثة يومية",
    quiz: "اختبار",
    progress: "تقدمي",
    profile: "الملف الشخصي",
    wordOfDay: "كلمة اليوم",
    dailyGoals: "أهداف اليوم",
    achievements: "الإنجازات",
    meaning: "المعنى",
    example: "مثال",
    translation: "ترجمة",
    loading: "جاري تحميل SpeakRise",
    nativeMeaning: (word, meaning) => `"${word}" تعني "${meaning}"`,
  },
  zh: {
    tagline: "聪明地学习英语",
    subtitle: "选择您的语言开始",
    chooseLanguage: "选择您的语言",
    continue: "继续",
    searchLang: "搜索语言...",
    welcomeBack: "欢迎回来",
    signIn: "登录",
    signUp: "注册",
    continueGoogle: "使用Google继续",
    orEmail: "或使用邮件",
    sendMagicLink: "发送魔法链接",
    dashboard: "仪表板",
    vocabulary: "词汇",
    grammar: "语法",
    reading: "阅读",
    conversation: "日常对话",
    quiz: "测验",
    progress: "我的进度",
    profile: "个人资料",
    wordOfDay: "今日单词",
    dailyGoals: "今日目标",
    achievements: "成就",
    meaning: "含义",
    example: "例句",
    translation: "翻译",
    loading: "正在加载 SpeakRise",
    nativeMeaning: (word, meaning) => `"${word}"的意思是"${meaning}"`,
  },
  de: {
    tagline: "Englisch auf die smarte Art lernen",
    subtitle: "Wähle deine Sprache zum Starten",
    chooseLanguage: "Wähle deine Sprache",
    continue: "Weiter",
    searchLang: "Sprache suchen...",
    welcomeBack: "Willkommen zurück",
    signIn: "Anmelden",
    signUp: "Registrieren",
    continueGoogle: "Mit Google fortfahren",
    orEmail: "oder mit Email",
    sendMagicLink: "Magic Link senden",
    dashboard: "Dashboard",
    vocabulary: "Vokabular",
    grammar: "Grammatik",
    reading: "Lesen",
    conversation: "Tägliches Gespräch",
    quiz: "Quiz",
    progress: "Mein Fortschritt",
    profile: "Profil",
    wordOfDay: "Wort des Tages",
    dailyGoals: "Tagesziele",
    achievements: "Erfolge",
    meaning: "Bedeutung",
    example: "Beispiel",
    translation: "Übersetzung",
    loading: "SpeakRise wird geladen",
    nativeMeaning: (word, meaning) => `"${word}" bedeutet "${meaning}"`,
  },
  pt: {
    tagline: "Aprenda inglês de forma inteligente",
    subtitle: "Escolha seu idioma para começar",
    chooseLanguage: "Escolha seu idioma",
    continue: "Continuar",
    searchLang: "Pesquisar idioma...",
    welcomeBack: "Bem-vindo de volta",
    signIn: "Entrar",
    signUp: "Cadastrar",
    continueGoogle: "Continuar com Google",
    orEmail: "ou com Email",
    sendMagicLink: "Enviar link mágico",
    dashboard: "Painel",
    vocabulary: "Vocabulário",
    grammar: "Gramática",
    reading: "Leitura",
    conversation: "Conversa diária",
    quiz: "Questionário",
    progress: "Meu progresso",
    profile: "Perfil",
    wordOfDay: "Palavra do dia",
    dailyGoals: "Metas do dia",
    achievements: "Conquistas",
    meaning: "Significado",
    example: "Exemplo",
    translation: "Tradução",
    loading: "Carregando SpeakRise",
    nativeMeaning: (word, meaning) => `"${word}" significa "${meaning}"`,
  },
  ru: {
    tagline: "Учите английский умно",
    subtitle: "Выберите язык для начала",
    chooseLanguage: "Выберите язык",
    continue: "Продолжить",
    searchLang: "Поиск языка...",
    welcomeBack: "С возвращением",
    signIn: "Войти",
    signUp: "Зарегистрироваться",
    continueGoogle: "Продолжить с Google",
    orEmail: "или по Email",
    sendMagicLink: "Отправить Magic Link",
    dashboard: "Панель управления",
    vocabulary: "Словарный запас",
    grammar: "Грамматика",
    reading: "Чтение",
    conversation: "Ежедневный разговор",
    quiz: "Викторина",
    progress: "Мой прогресс",
    profile: "Профиль",
    wordOfDay: "Слово дня",
    dailyGoals: "Цели на день",
    achievements: "Достижения",
    meaning: "Значение",
    example: "Пример",
    translation: "Перевод",
    loading: "Загрузка SpeakRise",
    nativeMeaning: (word, meaning) => `"${word}" означает "${meaning}"`,
  },
  ja: {
    tagline: "スマートに英語を学ぼう",
    subtitle: "始めるために言語を選択してください",
    chooseLanguage: "言語を選択してください",
    continue: "続ける",
    searchLang: "言語を検索...",
    welcomeBack: "おかえりなさい",
    signIn: "サインイン",
    signUp: "サインアップ",
    continueGoogle: "Googleで続ける",
    orEmail: "またはEmailで",
    sendMagicLink: "マジックリンクを送る",
    dashboard: "ダッシュボード",
    vocabulary: "語彙",
    grammar: "文法",
    reading: "読解",
    conversation: "日常会話",
    quiz: "クイズ",
    progress: "私の進捗",
    profile: "プロフィール",
    wordOfDay: "今日の単語",
    dailyGoals: "今日の目標",
    achievements: "実績",
    meaning: "意味",
    example: "例文",
    translation: "翻訳",
    loading: "SpeakRise を読み込んでいます",
    nativeMeaning: (word, meaning) => `"${word}"の意味は"${meaning}"です`,
  },
  sw: {
    tagline: "Jifunze Kiingereza kwa njia ya akili",
    subtitle: "Chagua lugha yako kuanza",
    chooseLanguage: "Chagua lugha yako",
    continue: "Endelea",
    searchLang: "Tafuta lugha...",
    welcomeBack: "Karibu tena",
    signIn: "Ingia",
    signUp: "Jisajili",
    continueGoogle: "Endelea na Google",
    orEmail: "au kwa Email",
    sendMagicLink: "Tuma Magic Link",
    dashboard: "Dashibodi",
    vocabulary: "Msamiati",
    grammar: "Sarufi",
    reading: "Kusoma",
    conversation: "Mazungumzo ya kila siku",
    quiz: "Maswali",
    progress: "Maendeleo yangu",
    profile: "Wasifu",
    wordOfDay: "Neno la leo",
    dailyGoals: "Malengo ya leo",
    achievements: "Mafanikio",
    meaning: "Maana",
    example: "Mfano",
    translation: "Tafsiri",
    loading: "Inapakia SpeakRise",
    nativeMeaning: (word, meaning) => `"${word}" inamaanisha "${meaning}"`,
  },
};

// Word meanings in each native language
const WORD_MEANINGS = {
  Hello: { hi:"नमस्ते", bn:"হ্যালো", te:"హలో", ta:"வணக்கம்", mr:"नमस्कार", gu:"નમસ્તે", kn:"ನಮಸ್ಕಾರ", ml:"ഹലോ", pa:"ਸਤ ਸ੍ਰੀ ਅਕਾਲ", ur:"ہیلو", fr:"Bonjour", es:"Hola", ar:"مرحبا", zh:"你好", de:"Hallo", pt:"Olá", ru:"Привет", ja:"こんにちは", sw:"Habari" },
  "Thank you": { hi:"धन्यवाद", bn:"ধন্যবাদ", te:"ధన్యవాదాలు", ta:"நன்றி", mr:"धन्यवाद", gu:"આભાર", kn:"ಧನ್ಯವಾದ", ml:"നന്ദി", pa:"ਧੰਨਵਾਦ", ur:"شکریہ", fr:"Merci", es:"Gracias", ar:"شكرا", zh:"谢谢", de:"Danke", pt:"Obrigado", ru:"Спасибо", ja:"ありがとう", sw:"Asante" },
  Please: { hi:"कृपया", bn:"দয়া করে", te:"దయచేసి", ta:"தயவுசெய்து", mr:"कृपया", gu:"કૃપા કરીને", kn:"ದಯವಿಟ್ಟು", ml:"ദയവായി", pa:"ਕਿਰਪਾ ਕਰਕੇ", ur:"براہ کرم", fr:"S'il vous plaît", es:"Por favor", ar:"من فضلك", zh:"请", de:"Bitte", pt:"Por favor", ru:"Пожалуйста", ja:"どうぞ", sw:"Tafadhali" },
  Water: { hi:"पानी", bn:"পানি", te:"నీరు", ta:"தண்ணீர்", mr:"पाणी", gu:"પાણી", kn:"ನೀರು", ml:"വെള്ളം", pa:"ਪਾਣੀ", ur:"پانی", fr:"Eau", es:"Agua", ar:"ماء", zh:"水", de:"Wasser", pt:"Água", ru:"Вода", ja:"水", sw:"Maji" },
  Food: { hi:"खाना", bn:"খাবার", te:"ఆహారం", ta:"உணவு", mr:"अन्न", gu:"ખોરાક", kn:"ಆಹಾರ", ml:"ഭക്ഷണം", pa:"ਖਾਣਾ", ur:"کھانا", fr:"Nourriture", es:"Comida", ar:"طعام", zh:"食物", de:"Essen", pt:"Comida", ru:"Еда", ja:"食べ物", sw:"Chakula" },
  Beautiful: { hi:"सुंदर", bn:"সুন্দর", te:"అందమైన", ta:"அழகான", mr:"सुंदर", gu:"સુંદર", kn:"ಸುಂದರ", ml:"സുന്ദരം", pa:"ਸੁੰਦਰ", ur:"خوبصورت", fr:"Beau", es:"Hermoso", ar:"جميل", zh:"美丽", de:"Schön", pt:"Bonito", ru:"Красивый", ja:"美しい", sw:"Nzuri" },
};
